name: Elixir CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message , '[skip ci]')"

    services:
      db:
        image: postgres:11
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: "1.13.3" # Define the elixir version [required]
          otp-version: "24.2.1" # Define the OTP version [required]

      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Check Formatting
        run: mix format --check-formatted

      - name: Run Credo
        run: mix credo --strict

      - name: Check coverage
        run: mix coveralls.json
        env:
          MIX_ENV: test

      - name: Run codecov script
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov 
          ./codecov -t ${CODECOV_TOKEN}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Run tests
        run: mix test

  deploy:
    name: Deploy on gigalixir
    needs: build
    if: github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message , '[skip ci]')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0 # Checkout the whole branch

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.1

      - uses: mhanberg/gigalixir-action@v0.4.0
        with:
          GIGALIXIR_APP: informal-informal-civet
          GIGALIXIR_CLEAN: false
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_PASSWORD: ${{ secrets.GIGALIXIR_PASSWORD }}
          MIGRATIONS: false
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
